field: 21f106b8-83b2-4648-9e70-94adc36fab96 # FS List
fieldLayouts:
  5443b8e4-8d58-4692-b5ff-a590a2d5dc7b:
    tabs:
      -
        elements:
          -
            fieldUid: c514881b-8cba-4ba9-8eda-bafe5e03ead3 # Course Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7955370d-671d-4fd3-9ddf-b3ffa06ecdf7 # Course Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7955370d-671d-4fd3-9ddf-b3ffa06ecdf7: # Course Image
    columnSuffix: mmwvrebp
    contentColumnType: string
    fieldGroup: null
    handle: courseImage
    instructions: ''
    name: 'Course Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c514881b-8cba-4ba9-8eda-bafe5e03ead3: # Course Name
    columnSuffix: wefbqtue
    contentColumnType: text
    fieldGroup: null
    handle: courseName
    instructions: ''
    name: 'Course Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: fsCourses
name: 'FS Courses'
sortOrder: 1
