field: 258bd81c-4519-4b01-9641-5ac9866ae82a # What We Do Items
fieldLayouts:
  9041f21e-2b90-43a3-89eb-ad8a09375d47:
    tabs:
      -
        elements:
          -
            fieldUid: e6d6f23c-0f24-45a8-b2cc-25b4db286154 # Item Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b1ccfcfc-10bd-4989-ae3b-dc533efffc74 # Item Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd941a9e-524d-4a66-9e4b-b431128c00ab # Item Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f4860a69-f49f-4207-a5a5-455f0c60e75a # Item Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b1ccfcfc-10bd-4989-ae3b-dc533efffc74: # Item Content
    columnSuffix: vjhtvpgz
    contentColumnType: text
    fieldGroup: null
    handle: itemContent
    instructions: ''
    name: 'Item Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd941a9e-524d-4a66-9e4b-b431128c00ab: # Item Image
    columnSuffix: cnbeuqgc
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: ''
    name: 'Item Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e6d6f23c-0f24-45a8-b2cc-25b4db286154: # Item Heading
    columnSuffix: oxjzfdug
    contentColumnType: text
    fieldGroup: null
    handle: itemHeading
    instructions: ''
    name: 'Item Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f4860a69-f49f-4207-a5a5-455f0c60e75a: # Item Type
    columnSuffix: svfuchte
    contentColumnType: smallint(1)
    fieldGroup: null
    handle: itemType
    instructions: 'This changes how the items are displayed, ''0'' is a long card and ''1'' is a short card. Alternating types of 1 and 2 are needed for the content to line up correctly.'
    name: 'Item Type'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 0
      max: 1
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: items
name: Items
sortOrder: 1
