field: fea1e2b7-40e2-4f91-9032-82136bbe0309 # Organisation Info
fieldLayouts:
  73b14271-6771-4e04-916d-45f5a1a6685b:
    tabs:
      -
        elements:
          -
            fieldUid: 4d70caad-a88c-48cf-a48a-1f34eb8a70e8 # Org Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d4e8119-ad85-408d-8727-e0195dd495bd # Org Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 267cceaa-0983-4f7e-aecf-569f20454f62 # Link to Site
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4d70caad-a88c-48cf-a48a-1f34eb8a70e8: # Org Name
    columnSuffix: aakcrvpd
    contentColumnType: text
    fieldGroup: null
    handle: orgName
    instructions: ''
    name: 'Org Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6d4e8119-ad85-408d-8727-e0195dd495bd: # Org Description
    columnSuffix: hkbvqwgm
    contentColumnType: text
    fieldGroup: null
    handle: orgDescription
    instructions: ''
    name: 'Org Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  267cceaa-0983-4f7e-aecf-569f20454f62: # Link to Site
    columnSuffix: sfodykwz
    contentColumnType: text
    fieldGroup: null
    handle: linkToSite
    instructions: ''
    name: 'Link to Site'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: org
name: Org
sortOrder: 1
