field: c028f2c9-1328-4db9-8982-5c2cdd412695 # Programme List
fieldLayouts:
  35f8787f-dc37-4333-89f5-46953cfbaf02:
    tabs:
      -
        elements:
          -
            fieldUid: 2ef70885-9a61-4132-b9c7-c7599db82436 # Program Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 749acd1b-2bbc-4e85-9132-3842c0b12e06 # Programme Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2ef70885-9a61-4132-b9c7-c7599db82436: # Program Name
    columnSuffix: ahzmghza
    contentColumnType: text
    fieldGroup: null
    handle: programName
    instructions: ''
    name: 'Program Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  749acd1b-2bbc-4e85-9132-3842c0b12e06: # Programme Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: programmeImage
    instructions: ''
    name: 'Programme Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: programmes
name: Programmes
sortOrder: 1
