field: 9535810e-7f85-4814-b848-16f889e7477f # CTA List
fieldLayouts:
  4abf6484-1cef-433d-9042-43b06dcf1d0d:
    tabs:
      -
        elements:
          -
            fieldUid: 0cabfdf7-3657-4649-aac3-7c826b0a027d # Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed472fd5-7d72-4ee5-af6a-1b4bafde337e # Question Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0cabfdf7-3657-4649-aac3-7c826b0a027d: # Question
    columnSuffix: xvecxreh
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: ''
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed472fd5-7d72-4ee5-af6a-1b4bafde337e: # Question Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: questionImage
    instructions: ''
    name: 'Question Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a1d35375-fad3-43fb-a1ed-44da484a56e9' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: questions
name: Questions
sortOrder: 1
