fieldLayouts:
  d11dd92f-5de6-4321-b0b0-f1f77a08ef64:
    tabs:
      -
        elements:
          -
            fieldUid: 5a512b18-6a4d-42d0-94c4-c37d8d60203b # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: index
hasTitleField: false
name: Index
section: 195006e8-7966-454b-8cd8-0942f09f79c6 # Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
