fieldLayouts:
  d11dd92f-5de6-4321-b0b0-f1f77a08ef64:
    tabs:
      -
        elements:
          -
            fieldUid: 5a512b18-6a4d-42d0-94c4-c37d8d60203b # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b577d2aa-b61c-4b57-b934-acbb22bf7b63 # heroImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6d2296d-2220-4a74-94d7-a03275034d57 # Hero Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b19e811-657a-4e02-a763-2fbaa7dc07a0 # Who We Are Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35c4947d-43eb-4d8f-a09d-139d6ebcdffc # Who We Are Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b17d671-4851-4d33-b63a-26eb6f430c8b # Who We Are 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 388bdc47-fb9f-499d-8b42-33853447db88 # Who We Are 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d0e9b6f-c9da-4d79-a63e-00ceec2834ad # What We Do Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: abd85c61-12aa-4ca9-9550-45caef0c2ae7 # What We Do Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56746bd2-f0d9-44ea-866b-c405cbe440e4 # Hero Styling
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 298f95e2-bd51-4cde-8b07-931edfdbce2d # Who We Are Styling
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7044c69-af30-4498-bde6-e74df1fbae70 # Hero Styling Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8567f973-c78d-4bea-85f6-047ce4e9c3fc # Who We Are Styling Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: index
hasTitleField: false
name: Index
section: 195006e8-7966-454b-8cd8-0942f09f79c6 # Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
