fieldLayouts:
  7b4ac83b-438a-4f9d-a68c-530877abbf41:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d1bbfc3c-09eb-4fb9-831e-28eb2092df3d # Reach And Impact Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74dd3015-fe0c-4e09-99f2-3f7f715bab0f # Reach and Impact Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 59e00648-62f0-4119-a6de-a010982c6d6c # Reach And Impact Stats Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42bc02db-d062-47ff-90fb-fa5e8fa1053f # Reach Stats
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: reachAndImpact
hasTitleField: true
name: 'Reach and Impact'
section: 919847da-318b-45ec-bed8-97615299d97a # Reach and Impact
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
