columnSuffix: qwblfydu
contentColumnType: text
fieldGroup: 19dddbad-59d7-4efd-ac2e-b7d71deb7c5f # What We Do
handle: item2Content
instructions: ''
name: 'Item 2 Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
