columnSuffix: hztbvutk
contentColumnType: text
fieldGroup: 9c6073a8-c901-4325-b199-2af389c8e856 # Organisations
handle: organisationsParagraph
instructions: ''
name: 'Organisations Paragraph'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
