columnSuffix: null
contentColumnType: string
fieldGroup: 9c6073a8-c901-4325-b199-2af389c8e856 # Organisations
handle: organisationInfo
instructions: ''
name: 'Organisation Info'
searchable: false
settings:
  contentTable: '{{%matrixcontent_organisationinfo}}'
  maxBlocks: '10'
  minBlocks: '3'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
