columnSuffix: aagimosn
contentColumnType: text
fieldGroup: 214101f9-132f-47de-90c5-bfa9338638ca # Partnerships
handle: partnershipTitle
instructions: ''
name: 'Partnership Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
