columnSuffix: null
contentColumnType: string
fieldGroup: 7b9504f3-0f44-4d8d-9157-366073044e9d # How Can We Partner
handle: programmeList
instructions: ''
name: 'Programme List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_programmelist}}'
  maxBlocks: '5'
  minBlocks: '5'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
