columnSuffix: ifjzkmne
contentColumnType: text
fieldGroup: d2d28287-fcee-4423-b368-21bf61e75978 # Reach And Impact
handle: reachAndImpactTitle
instructions: ''
name: 'Reach And Impact Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
