columnSuffix: null
contentColumnType: string
fieldGroup: d2d28287-fcee-4423-b368-21bf61e75978 # Reach And Impact
handle: reachStats
instructions: ''
name: 'Reach Stats'
searchable: false
settings:
  contentTable: '{{%matrixcontent_reachstats}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
