columnSuffix: null
contentColumnType: string
fieldGroup: 8d945038-12f0-4434-be16-282c0d4db6d4 # Success Stories
handle: testimonials
instructions: ''
name: Testimonials
searchable: false
settings:
  contentTable: '{{%matrixcontent_testimonials}}'
  maxBlocks: '5'
  minBlocks: '2'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
