columnSuffix: nltambvo
contentColumnType: text
fieldGroup: c8832791-7230-4319-b3b6-570098980b47 # Index
handle: whatWeDoSubtitle
instructions: ''
name: 'What We Do Subtitle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
