defaultPlacement: end
enableVersioning: true
handle: howCanWePartner
name: '8. How Can We Partner'
propagationMethod: all
siteSettings:
  67f41e09-e046-48b2-8922-8f5c03bbb14c: # Alf Public
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: how-can-we-partner
type: single
