defaultPlacement: end
enableVersioning: true
handle: index
name: Index
propagationMethod: all
siteSettings:
  67f41e09-e046-48b2-8922-8f5c03bbb14c: # ALF Public
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
